CREATE TABLE `TWITTER_USER` (
  `ID` bigint(20) NOT NULL PRIMARY KEY ,
  `NAME` varchar(255) CHARACTER SET  utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `SCREEN_NAME` varchar(255) DEFAULT NULL,
  `CREATED_AT` datetime DEFAULT NULL,
  `IS_VERIFIED` bit(1) DEFAULT NULL,
  `LOCATION` varchar(255) DEFAULT NULL,
  `FAVOURITES_COUNT` int(11) DEFAULT NULL,
  `FOLLOWERS_COUNT` int(11) DEFAULT NULL,
  `FRIENDS_COUNT` int(11) DEFAULT NULL,
  `STATUSES_COUNT` int(11) DEFAULT NULL
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE=INNODB;

CREATE TABLE `TWEET` (
  `ID` bigint(20) NOT NULL PRIMARY KEY ,
  `TWITTER_USER_ID` bigint(20) DEFAULT NULL,
  `CREATED_AT` datetime DEFAULT NULL,
  `TEXT` varchar(255) CHARACTER SET  utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `LANG` varchar(255) DEFAULT NULL,
  `FAVORITE_COUNT` int(11) DEFAULT NULL,
  `RETWEET_COUNT` int(11) DEFAULT NULL,
  `SOURCE` varchar(255) DEFAULT NULL,
  CONSTRAINT FK_TWEET_TWITTER_USER_ID FOREIGN KEY (TWITTER_USER_ID) REFERENCES TWITTER_USER(ID)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE=INNODB;

